DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

DROP TABLE IF EXISTS info;
CREATE TABLE info (
  id INTEGER AUTO_INCREMENT,
  PRIMARY KEY(id),
  name VARCHAR(20)
);

INSERT INTO info (name) VALUES('Jin');